name = "l4va/vault"
version = "0.0.7"
compiler = "v1.1.10"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'l4va/vault'"

[repository]
user = "l4va"
project = "vault"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
